#!/bin/bash
        COUNTER=0
	cd "${0%/*}"
	g++ Instr.cpp ISA.cpp main.cpp -std=c++11 -o r.out
	g++ outputParsing.cpp -o v.out
	g++ gold.cpp -o g.out
        while [  $COUNTER -lt 1 ]; do
		./r.out
		./build_s.sh
		iverilog CPU_tb.v -o designOutput.vvp
		vvp designOutput.vvp -> d_res.txt
		./g.out app.bin > g_res.txt
		./v.out
		let COUNTER=COUNTER+1
	done
